name: Renovate

on:
  workflow_call:
  workflow_dispatch:
  # TODO add schedule

concurrency: renovate

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Renovate JSON
        run: jq type .github/renovate.json
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.0.2
        env:
          LOG_LEVEL: debug
          # Onboarding not needed for self hosted
          RENOVATE_ONBOARDING: "false"
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
